export const games = [
    {
        name: "Assassin's Creed III",
        releaseDate: "2012-10-30",
        price: 39.99,
        platforms: ["PC", "PS3", "Xbox 360", "Wii U"],
        studio: "Ubisoft",
        director: "Alex Hutchinson",
        pic: "./PIC/assassin3.png",
    },
    {
        name: "Resident Evil 2",
        releaseDate: "1998-01-21",
        price: 39.99,
        platforms: ["PC", "PS1", "N64"],
        studio: "Capcom Production Studio 4",
        director: "Hideki Kamiya",
        pic: "./PIC/residentevil2.png",
    },
    {
        name: "Bloodborne",
        releaseDate: "2015-03-24",
        price: 59.99,
        platforms: ["PS4"],
        studio: "FromSoftware",
        director: "Hidetaka Miyazaki",
        pic: "./PIC/bloodborne.png",
    },
    {
        name: "Max Payne 3",
        releaseDate: "2012-05-15",
        price: 39.99,
        platforms: ["PC", "PS3", "Xbox 360"],
        studio: "Rockstar Games",
        director: "Sam Houser",
        pic: "./PIC/maxpayne3.png",
    },
    {
        name: "The Witcher 2: Assassins of Kings",
        releaseDate: "2011-05-17",
        price: 29.99,
        platforms: ["PC", "Xbox 360"],
        studio: "CD Projekt Red",
        director: "Adam Badowski",
        pic: "./PIC/thewitcher2.png",
    },
    {
        name: "Sekiro: Shadows Die Twice",
        releaseDate: "2019-03-22",
        price: 59.99,
        platforms: ["PC", "PS4", "Xbox One"],
        studio: "FromSoftware",
        director: "Hidetaka Miyazaki",
        pic: "./PIC/sekiro.png",
    },
    {
        name: "Devil May Cry",
        releaseDate: "2001-08-23",
        price: 29.99,
        platforms: ["PS2"],
        studio: "Capcom Production Studio 4",
        director: "Hideki Kamiya",
        pic: "./PIC/dmc.png",
    },
    {
        name: "Resident Evil 5",
        releaseDate: "2009-03-05",
        price: 29.99,
        platforms: ["PC", "PS3", "Xbox 360"],
        studio: "Capcom Production Studio 4",
        director: "Kenichi Ueda",
        pic: "./PIC/residentevil5.png",
    },
    {
        name: "The Witcher 3: Wild Hunt",
        releaseDate: "2015-05-19",
        price: 49.99,
        platforms: ["PC", "PS4", "Xbox One", "Nintendo Switch"],
        studio: "CD Projekt Red",
        director: "Konrad Tomaszkiewicz",
        pic: "./PIC/thewitcher3.png",
    },
    {
        name: "Resident Evil Code: Veronica",
        releaseDate: "2000-02-03",
        price: 39.99,
        platforms: ["PC", "Dreamcast", "PS2"],
        studio: "Capcom Production Studio 4",
        director: "Shinji Mikami",
        pic: "./PIC/residentevilCV.png",
    },
    {
        name: "Assassin's Creed Valhalla",
        releaseDate: "2020-11-10",
        price: 59.99,
        platforms: ["PC", "PS4", "PS5", "Xbox One", "Xbox Series X/S"],
        studio: "Ubisoft",
        director: "Ashraf Ismail",
        pic: "./PIC/assassinval.png",
    },
    {
        name: "Cyberpunk 2077",
        releaseDate: "2020-12-10",
        price: 59.99,
        platforms: ["PC", "PS4", "PS5", "Xbox One", "Xbox Series X/S"],
        studio: "CD Projekt Red",
        director: "Adam Badowski",
        pic: "./PIC/cyberpunk2077.png",
    },
    {
        name: "Splinter Cell: Blacklist",
        releaseDate: "2013-08-20",
        price: 39.99,
        platforms: ["PC", "PS3", "Xbox 360"],
        studio: "Ubisoft",
        director: "Patrick Redding",
        pic: "./PIC/splinterblacklist.png",
    },
    {
        name: "Hollow Knight",
        releaseDate: "2017-02-24",
        price: 14.99,
        platforms: ["PC", "Nintendo Switch", "PS4", "Xbox One"],
        studio: "Team Cherry",
        director: "Ari Gibson",
        pic: "./PIC/hollowknight.png",
    },
    {
        name: "Watch Dogs",
        releaseDate: "2014-05-27",
        price: 49.99,
        platforms: ["PC", "PS4", "Xbox One"],
        studio: "Ubisoft",
        director: "Jonathan Morin",
        pic: "./PIC/watchdog.png",
    },
    {
        name: "Red Dead Redemption 2",
        releaseDate: "2018-10-26",
        price: 59.99,
        platforms: ["PC", "PS4", "Xbox One"],
        studio: "Rockstar Games",
        director: "Rodney E. McCulloch",
        pic: "./PIC/rdr2.png",
    },
    {
        name: "Resident Evil 3: Nemesis",
        releaseDate: "1999-09-22",
        price: 39.99,
        platforms: ["PC", "PS1", "Dreamcast"],
        studio: "Capcom Production Studio 4",
        director: "Kazuhiro Aoyama",
        pic: "./PIC/residentevil3.png",
    },
    {
        name: "Assassin's Creed Odyssey",
        releaseDate: "2018-10-05",
        price: 59.99,
        platforms: ["PC", "PS4", "Xbox One"],
        studio: "Ubisoft",
        director: "Scott Phillips",
        pic: "./PIC/assassinody.png",
    },
    {
        name: "Resident Evil",
        releaseDate: "1996-03-22",
        price: 39.99,
        platforms: ["PC", "PS1"],
        studio: "Capcom Production Studio 4",
        director: "Shinji Mikami",
        pic: "./PIC/residentevil.png",
    },
    {
        name: "Far Cry 5",
        releaseDate: "2018-03-27",
        price: 59.99,
        platforms: ["PC", "PS4", "Xbox One"],
        studio: "Ubisoft",
        director: "Dan Hay",
        pic: "./PIC/farcry5.png",
    },
    {
        name: "Elden Ring",
        releaseDate: "2022-02-25",
        price: 59.99,
        platforms: ["PC", "PS4", "PS5", "Xbox One", "Xbox Series X/S"],
        studio: "FromSoftware",
        director: "Hidetaka Miyazaki",
        pic: "./PIC/EldenRing.png",
    },
    {
        name: "Dark Souls",
        releaseDate: "2011-09-22",
        price: 39.99,
        platforms: ["PC", "PS3", "Xbox 360"],
        studio: "FromSoftware",
        director: "Hidetaka Miyazaki",
        pic: "./PIC/DS1.png",
    },
    {
        name: "GTA V",
        releaseDate: "2013-09-17",
        price: 29.99,
        platforms: ["PC", "PS4", "Xbox One", "PS3", "Xbox 360"],
        studio: "Rockstar Games",
        director: "Leslie Benzies",
        pic: "./PIC/gta5.png",
    },
    {
        name: "L.A. Noire",
        releaseDate: "2011-05-17",
        price: 49.99,
        platforms: ["PC", "PS3", "Xbox 360"],
        studio: "Rockstar Games",
        director: "Brendan McNamara",
        pic: "./PIC/lanoire.png",
    },
    {
        name: "Assassin's Creed II",
        releaseDate: "2009-11-17",
        price: 39.99,
        platforms: ["PC", "PS3", "Xbox 360"],
        studio: "Ubisoft",
        director: "Patrice Désilets",
        pic: "./PIC/assassin2.png",
    }
];
